file(GET_RUNTIME_DEPENDENCIES
    EXECUTABLES ${EXECUTABLE}
    RESOLVED_DEPENDENCIES_VAR RESOLVED_DEPS
    UNRESOLVED_DEPENDENCIES_VAR UNRESOLVED_DEPS
    DIRECTORIES ${CMAKE_INSTALL_PREFIX}
)

foreach(DEP ${RESOLVED_DEPS})
    file(COPY ${DEP} DESTINATION ${CMAKE_INSTALL_PREFIX})
endforeach()

if(UNRESOLVED_DEPS)
    message(WARNING "Unresolved dependencies: ${UNRESOLVED_DEPS}")
endif()